{
    "lock_version": 3,
    "position": 10,
    "publish": True,
    "ref_id": "ref56_ifi",
    "title": "Faculty meeting minutes",
    "display_string": "Faculty meeting minutes, 1895 September 14 - 1897 March 17",
    "restrictions_apply": False,
    "created_by": "admin",
    "last_modified_by": "tanguay",
    "create_time": "2016-10-11T20:36:08Z",
    "system_mtime": "2023-07-24T17:46:25Z",
    "user_mtime": "2022-01-07T20:41:33Z",
    "suppressed": False,
    "is_slug_auto": False,
    "level": "item",
    "jsonmodel_type": "archival_object",
    "external_ids": [
        {
            "external_id": "39951",
            "source": "Archivists Toolkit Database::RESOURCE_COMPONENT",
            "created_by": "tanguay",
            "last_modified_by": "tanguay",
            "create_time": "2022-01-07T20:41:34Z",
            "system_mtime": "2022-01-07T20:41:34Z",
            "user_mtime": "2022-01-07T20:41:34Z",
            "jsonmodel_type": "external_id",
        }
    ],
    "subjects": [],
    "linked_events": [],
    "extents": [
        {
            "lock_version": 0,
            "number": "1",
            "created_by": "tanguay",
            "last_modified_by": "tanguay",
            "create_time": "2022-01-07T20:41:33Z",
            "system_mtime": "2022-01-07T20:41:33Z",
            "user_mtime": "2022-01-07T20:41:33Z",
            "portion": "whole",
            "extent_type": "volume(s)",
            "jsonmodel_type": "extent",
        }
    ],
    "lang_materials": [
        {
            "lock_version": 0,
            "created_by": "tanguay",
            "last_modified_by": "tanguay",
            "create_time": "2022-01-07T20:41:33Z",
            "system_mtime": "2022-01-07T20:41:33Z",
            "user_mtime": "2022-01-07T20:41:33Z",
            "jsonmodel_type": "lang_material",
            "notes": [],
            "language_and_script": {
                "lock_version": 0,
                "created_by": "tanguay",
                "last_modified_by": "tanguay",
                "create_time": "2022-01-07T20:41:33Z",
                "system_mtime": "2022-01-07T20:41:33Z",
                "user_mtime": "2022-01-07T20:41:33Z",
                "language": "eng",
                "script": "Latn",
                "jsonmodel_type": "language_and_script",
            },
        }
    ],
    "dates": [
        {
            "lock_version": 0,
            "expression": "1895 September 14 - 1897 March 17",
            "begin": "1895-09-14",
            "end": "1897-03-17",
            "created_by": "tanguay",
            "last_modified_by": "tanguay",
            "create_time": "2022-01-07T20:41:33Z",
            "system_mtime": "2022-01-07T20:41:33Z",
            "user_mtime": "2022-01-07T20:41:33Z",
            "date_type": "inclusive",
            "label": "creation",
            "jsonmodel_type": "date",
        }
    ],
    "external_documents": [],
    "rights_statements": [],
    "linked_agents": [],
    "import_previous_arks": [],
    "ancestors": [
        {"ref": "/repositories/2/archival_objects/304", "level": "series"},
        {"ref": "/repositories/2/resources/2", "level": "collection"},
    ],
    "instances": [
        {
            "lock_version": 0,
            "created_by": "tanguay",
            "last_modified_by": "tanguay",
            "create_time": "2022-01-07T20:41:33Z",
            "system_mtime": "2022-01-07T20:41:33Z",
            "user_mtime": "2022-01-07T20:41:33Z",
            "instance_type": "mixed_materials",
            "jsonmodel_type": "instance",
            "is_representative": False,
            "sub_container": {
                "lock_version": 0,
                "created_by": "tanguay",
                "last_modified_by": "tanguay",
                "create_time": "2022-01-07T20:41:33Z",
                "system_mtime": "2022-01-07T20:41:33Z",
                "user_mtime": "2022-01-07T20:41:33Z",
                "jsonmodel_type": "sub_container",
                "top_container": {"ref": "/repositories/2/top_containers/224"},
            },
        }
    ],
    "notes": [
        {
            "jsonmodel_type": "note_multipart",
            "subnotes": [
                {"jsonmodel_type": "note_text", "content": "Open.", "publish": True}
            ],
            "type": "accessrestrict",
            "rights_restriction": {"local_access_restriction_type": []},
            "persistent_id": "caa7be7ed6acc04edc39c9da3fd1cb94",
            "publish": True,
        }
    ],
    "accession_links": [],
    "uri": "/repositories/2/archival_objects/314",
    "repository": {"ref": "/repositories/2"},
    "resource": {"ref": "/repositories/2/resources/2"},
    "parent": {"ref": "/repositories/2/archival_objects/304"},
    "has_unpublished_ancestor": False,
}
